### PR TITLE
Fix the migration feature

### LINKED ISSUE #108: The migration feature is broken
Current version: 5.1.1

I'm making this because it was unexpected behavior. I wanted to use migrations, and applying them works fine the first time. However, internally, this app adds a key to track which migrations have been run, by default:
```
"__internal__": {
    "migrations": {
      "version": version_number
    }
  }
```

The underlying assumption based upon the documentation here and on the `conf` package this uses, is that the version_number will be the version of my application's package.json
However, using electron-store, it applies the version of electron-store instead, so at the moment it is always 5.1.1 regardless of my app's version, causing my future migrations not to run if they are below that.

Not sure if this should be fixed in this app to somehow point correctly to my app's package.json or in `conf` code's check of what package.json to use.

### PR DESCRIPTION
**Pull request by pgherveou**
Looks like now it's picking up the module package.json version
Not sure how you would like to test this. Happy to add a test if you have any recommendations!

Closes #121
Fixes #108

### CODE REVIEW

File: test.js [hunk 1]
```diff
@@ -32,3 +32,9 @@ test('cwd option', async t => {
 	fs.unlinkSync(storagePath);
 	fs.unlinkSync(storagePath2);
 });
+
+test('projectVersion', async t => {
+	const storagePath = await run('fixture.js');
+	t.deepEqual(JSON.parse(fs.readFileSync(storagePath, 'utf8')), {ava: '🚀'});
+	fs.unlinkSync(storagePath);
+});
```
Comment (pgherveou) [inline test.js:40]:
```suggestion
```
