### PR TITLE
Fix compatibility with Electron 12

### LINKED ISSUE #152: Remote will be deprecated, Electron-store relies on remote
Remote will be deprecated in version 12, and completely removed in electron 14. 
While it's not right around the corner, it's not too far away. Seeing how this library relies on Remote to be usable in the renderer (as far as I know), I thought I'd post this issue. 

Although it won't be in electron, I do believe you'll be able to use Remote as a library, but I'm not sure.
For more information, check https://github.com/electron/electron/issues/21408

### PR DESCRIPTION
**Pull request by MehediH**
Hi! Attempting to fix #152 here.

As Electron is deprecating `remote`, this PR removes the module's dependency on remote. The change requires users to first call the new `StoreInit()` function exported by the module in the Main process in order to set up the `ipcMain` handler which enables communication from the renderer process. 

The default export, as a result, has been tweaked and the module now needs to be used as such:

```javascript
// main.js

const { Store, StoreInit } = require('electron-store');

StoreInit(); // needed for communication between Main/Renderer processes 

const store = new Store({ cwd: 'foo' });
store.set('unicorn', '🦄');
```

And on the renderer process, the usage is practically the same, except from the import:
```javascript
// renderer.js
const { Store } = require('electron-store');

const store = new Store({cwd: 'foo'});
console.log(store.get("unicorn"))
```

Happy to improve this further as needed -- will also update the docs and usage instructions if this looks good @sindresorhus!

### CODE REVIEW

**Comment by sindresorhus** [comment]
Couldn't just `new Store()` initialize it (if it's on the main process)? Why a separate method?

The IPC communication should be synchronous.

**Comment by MehediH** [comment]
Good point! I have moved the initializer into the constructor so calling `new Store()` within the main process will set up the `ipcMain` handlers. It will still throw an error if it can't find the handler for the message when called from a renderer process. 

> The IPC communication should be synchronous.

Could you please clarify how this can be achieved? I have tried `ipcRenderer.sendSync()` but that blocks the renderer process while it waits for a reply, and thus there is a noticeable delay in the app opening up. 

Would appreciate any pointers :)

**Comment by MehediH** [comment]
Also, I wonder what the best approach for the initializer would be? Having a static `init()` like in [e55ebe6](https://github.com/sindresorhus/electron-store/pull/157/commits/e55ebe62d358342ef3774d65177ab9f804634274) will allow the user to set-up the `ipcMain` handlers on the Main process without actually creating the Store, in case they only need to use it in the Renderer. 

The other option like in [3fc1e35](https://github.com/sindresorhus/electron-store/pull/157/commits/3fc1e351dd95c485e3b2143343723bbb0c8d527b) will make the module work as is after the update, so I guess that is more beneficial, but that's only the case if they are creating a Store in the main process first. That will break things for those who just have a Store in the renderer process after the update, and they will need to create a Store in the main process first. 

Thoughts?

**Comment by sindresorhus** [comment]
> Could you please clarify how this can be achieved? I have tried ipcRenderer.sendSync() but that blocks the renderer process while it waits for a reply, and thus there is a noticeable delay in the app opening up.

That's how it currently works though. `remote.require` uses synchronous IPC.

The problem with async is that you can get into a situation where the renderer tries to use the store before the async IPC has replied.

> Also, I wonder what the best approach for the initializer would be? Having a static init() like in e55ebe6 will allow the user to set-up the ipcMain handlers on the Main process without actually creating the Store, in case they only need to use it in the Renderer.

We could also add a static `Store.initRenderer()` or something for that case.

**Comment by sindresorhus** [comment]
// @dertieran

**Comment by MehediH** [comment]
> That's how it currently works though. remote.require uses synchronous IPC.

Ah, I didn't know this. Will switch to `ipcRenderer.sendSync()` with a commit soon :)

> We could also add a static Store.initRenderer() or something for that case.

Yes, so by default if the user uses the Store in the Main process, they don't have to do anything else to use it in Rendered. But if they only use it in Renderer, they will have to call the `initRenderer` on the Main. I think that makes sense, will just have to document this clearly.

Is there anything else I should tweak or anything that's blocking the merge? 😊 Will get the first two changes committed by Monday.

**Comment by sindresorhus** [comment]
> Yes, so by default if the user uses the Store in the Main process, they don't have to do anything else to use it in the Renderer. But if they only use it in Renderer, they will have to call the initRenderer on the Main. I think that makes sense, will just have to document this clearly.

👍

**Comment by MehediH** [comment]
Okay I just made the changes you requested @sindresorhus, also updated a bit of the README but please let me know if I should update it more to clarify things 👍🏼

File: index.js [hunk 1]
```diff
@@ -25,9 +47,25 @@ class ElectronStore extends Conf {
...
+	// Initializier to set up the ipcMain handler for communication between renderer and main prrocess
+	// When the user does not create a new Store in the main process
+	static initRenderer() {
+		if (!ipcMain || !app) {
+			throw new Error('Electron Store: you need to call initRenderer() from the Main process.');
+		}
+
+		ipcMain.on('electron-store-comms', event => {
+			event.returnValue = {
+				defaultCwd: app.getVersion(),
```
Comment (runyanp) [inline index.js:63]: The values for `defaultCwd` and `appVersion` here seem backwards at first glance. Is that intentional?

Comment (MehediH) [reply index.js]: Nope, thank you for pointing this out!

File: index.js [hunk 2]
```diff
@@ -1,20 +1,42 @@
...
+			ipcMain.on('electron-store-comms', event => {
+				event.returnValue = {
+					defaultCwd: app.getPath('userData'),
+					appVersion: app.getVersion()
+				};
+			});
+
+			defaultCwd = app.getPath('userData');
+			appVersion = app.getVersion();
+		}
```
Comment (sindresorhus) [inline index.js:31]: I think this would be more readable if you made a general function called `getFromMain` that accepts a callback where you can do return the values and if the process is already main, it would just return them directly. That way you wouldn't need to duplicate the logic to get the values.

File: index.js [hunk 3]
```diff
@@ -25,9 +47,25 @@ class ElectronStore extends Conf {
...
+		if (!ipcMain || !app) {
+			throw new Error('Electron Store: you need to call initRenderer() from the Main process.');
+		}
+
+		ipcMain.on('electron-store-comms', event => {
+			event.returnValue = {
+				defaultCwd: app.getPath('userData'),
+				appVersion: app.getVersion()
+			};
+		});
```
Comment (sindresorhus) [inline index.js:66]: This should not be duplicated here. Find a way to unify the logic.

File: index.js [hunk 4]
```diff
@@ -25,9 +47,25 @@ class ElectronStore extends Conf {
 
 		options.configName = options.name;
 		delete options.name;
+
 		super(options);
 	}
 
+	// Initializier to set up the ipcMain handler for communication between renderer and main prrocess
+	// When the user does not create a new Store in the main process
+	static initRenderer() {
```
Comment (sindresorhus) [inline index.js:56]: This needs to be documented in the readme and index.d.ts

File: index.js (hunk 2 above)
Comment (MehediH) [reply index.js:31]: Hmm, I am not quite sure if that is possible. I tried unifying the code before, but because `ElectronStore` is a subclass of `Conf`, we can't call any other class functions before calling `super()`. See: https://eslint.org/docs/rules/no-this-before-super. Unless you mean a regular function that's outside the `ElectornStore` class? Would like some clarification :)

Comment (sindresorhus) [reply index.js:31]: Regular function outside the class.

File: index.js (hunk 4 above)
Comment (MehediH) [reply index.js:63]: I have unified the `ipc` code and added the documentation for `initRenderer()` to index.d.ts. However, on the readme file, where would be an appropriate place to add this? Since it is a static function and is not an instance function, Any ideas?

File: index.js [hunk 5]
```diff
@@ -4,6 +4,25 @@ const electron = require('electron');
...
+		throw new Error('Electron Store: you need to call initRenderer() from the Main process.');
+	}
+
+	const appData = {
+		defaultCwd: app.getPath('userData'),
+		appVersion: app.getVersion()
+	};
+
+	// Set up the ipcMain handler for communication between renderer and main prrocess
+	ipcMain.on('electron-store-comms', event => {
```
Comment (sindresorhus) [inline index.js:19]:
```suggestion
	ipcMain.on('electron-store-get-data', event => {
```

File: index.js [hunk 6]
```diff
@@ -4,6 +4,25 @@ const electron = require('electron');
 const {app, ipcMain, ipcRenderer} = electron;
 const Conf = require('conf');
 
+// Set up the ipcMain handler for communication between renderer and main prrocess
+const initComms = () => {
```
Comment (sindresorhus) [inline index.js:8]: Don't use abbreviations.

File: index.js (hunk 4 above)
Comment (sindresorhus) [reply index.js:63]: Below https://github.com/sindresorhus/electron-store#openineditor as a `###` item.

File: index.d.ts [hunk 7]
```diff
@@ -57,6 +57,12 @@ declare class ElectronStore<T extends Record<string, any> = Record<string, unkno
 	Open the storage file in the user's editor.
 	*/
 	openInEditor(): void;
+
+	/**
+	Initializier that sets up the required ipcMain listener
+	when the user does not create a new Store in the main process
```
Comment (sindresorhus) [inline index.d.ts:63]: Don't hard-wrap

File: index.d.ts [hunk 8]
```diff
@@ -57,6 +57,12 @@ declare class ElectronStore<T extends Record<string, any> = Record<string, unkno
...
+	*/
+	ipcRenderer(): void;
```
Comment (sindresorhus) [inline index.d.ts:65]: Incorrect name.

File: index.js [hunk 9]
```diff
@@ -25,9 +54,16 @@ class ElectronStore extends Conf {
...
 		options.configName = options.name;
 		delete options.name;
+
 		super(options);
 	}
 
+	// Initializier that calls initComms() to set-up the required ipcMain listener
+	// When the user does not create a new Store in the main process
+	static initRenderer() {
+		return initComms();
```
Comment (sindresorhus) [inline index.js:64]: This should not return.

File: readme.md [hunk 10]
```diff
@@ -4,9 +4,7 @@
 
 Electron doesn't have a built-in way to persist user preferences and other data. This module handles that for you, so you can focus on building your app. The data is saved in a JSON file named config.json in [`app.getPath('userData')`](https://electronjs.org/docs/api/app#appgetpathname).
 
-You can use this module directly in both the main and renderer process.
-
-# When on Electron 10 or later, you need to enable the [`enableRemoteModule`](https://www.electronjs.org/docs/api/browser-window#new-browserwindowoptions) option to be able to use it directly in the renderer process.
+You can use this module directly in both the main and renderer process. For use in the renderer process, you need to create a `new Store()` in the main process, or call `Store.initRenderer()` in the main process first. This is due to the [security issues](https://github.com/electron/electron/issues/21408) of the `remote` module in Electron.
```
Comment (sindresorhus) [inline readme.md:7]: This is not the place to document "why" Electron no longer has the `remote` module.

**Review by sindresorhus — CHANGES_REQUESTED** [review]

File: index.d.ts [hunk 11]
```diff
@@ -57,6 +57,11 @@ declare class ElectronStore<T extends Record<string, any> = Record<string, unkno
 	Open the storage file in the user's editor.
 	*/
 	openInEditor(): void;
+
+	/**
+	Initializier that sets up the required ipcMain listener when the user does not create a new Store in the main process.
```
Comment (sindresorhus) [inline index.d.ts:62]: This should be in sync with the readme.

File: readme.md [hunk 12]
```diff
@@ -333,6 +331,27 @@ Get the path to the storage file.
 
 Open the storage file in the user's editor.
 
+### initRenderer()
+
+Initializier to set-up the required `ipc` communication channels for the module when a `Store` instance is not created in the main process. Use this if you are using a `Store` instance in the Electron renderer prrocess only.
```
Comment (sindresorhus) [inline readme.md:336]:
```suggestion
Initializer to set up the required `ipc` communication channels for the module when a `Store` instance is not created in the main process. Use this if you are using a `Store` instance in the Electron renderer process only.
```

File: readme.md [hunk 13]
```diff
@@ -333,6 +331,27 @@ Get the path to the storage file.
...
+
+Store.initRenderer();
+```
+
+And in the renderer process:
+```js
+const Store = require('electron-store');
+
+store.set('unicorn', '🦄');
+console.log(store.get('unicorn'));
```
Comment (sindresorhus) [inline readme.md:351]: The code should be valid.

File: readme.md [hunk 14]
```diff
@@ -333,6 +331,27 @@ Get the path to the storage file.
...
+
+In the main process:
+
+```js
+const Store = require('electron-store');
+
+Store.initRenderer();
+```
+
+And in the renderer process:
```
Comment (sindresorhus) [inline readme.md:346]:
```suggestion
And in the renderer process:

```

File: readme.md (hunk 12 above)
Comment (sindresorhus) [reply readme.md:336]: I think this could be shortened to a single sentence.

File: index.js [hunk 15]
```diff
@@ -25,9 +54,16 @@ class ElectronStore extends Conf {
 
 		options.configName = options.name;
 		delete options.name;
+
 		super(options);
 	}
 
+	// Initializier that calls initDataListener() to set-up the required ipcMain listener
+	// When the user does not create a new Store in the main process
```
Comment (sindresorhus) [inline index.js:62]: This comment is moot. It's better document in the TS file.

File: readme.md (hunk 12 above)
Comment (MehediH) [reply readme.md:336]: Haha yeah, sorry about that!

**Comment by Art4** [comment]
I think the mandatory call of `Store.initRenderer()` will confuse some users if they only want to use the store in the renderer. This will also lead to confusion with users who only use the store in main. We should make it clearer.

Suggestion: We are disabling support in renderer by default so the store will only work in main and support for the renderer must be explicit enabled.

### renderer is disabled by default

So the default in main will look like this:

```js
// in main
const Store = require('electron-store');

const store = new Store();
```

If someone trying to use it in renderer it should return an error.

```js
// in renderer
const Store = require('electron-store');

const store = new Store();
// ERROR: You have to active renderer integration in your main.js
```

### activate renderer integration

To active the store in the renderer one has to call the static method `enableRendererIntegration()`.

```js
// in main
const Store = require('electron-store');

Store.enableRendererIntegration();
```

```js
// in renderer
const Store = require('electron-store');

const store = new Store();

store.set('unicorn', '🦄');
console.log(store.get('unicorn'));
```

This should be an elegant an clear way to active the ipc in renderer.

What do you think?

**Comment by dertieran** [comment]
I think there are many package that will have this problem.
*([7 alone from sindre](https://github.com/sindresorhus/electron-util/issues/36#issuecomment-749622810) :smile:)*

Over at `electron-util` I also took the approach of exposing a [`initializeRemote`](https://github.com/sindresorhus/electron-util/pull/37) function but didn't really like it.
May main concern was that using `@electron/remote` is somewhat discouraged.

I proposed a pattern that basically exposes a `electron-util/main` and `electron-util/renderer` module.
The `main` module containing code that needs to be executed in `main` process and vice versa for the `renderer` module.
*(Of Course there can also be shared code between those, that can run in either the `main` or `renderer` process.)*
Then the developer can decide if they want to expose the `main` process module to the renderer by using the `@electron/remote` themself.

Would be great to get input on this idea by other developers who also are facing this problem.
Because I personally use most of these package in the `main` process only, so I only know this use case.
We can also discuss this in https://github.com/sindresorhus/electron-util/issues/36 and this PR can be keept as is.

**Comment by Art4** [comment]
@dertieran This PR will remove the dependency for the remote module. Splitting the repo for main and renderer seems a bit over engineered to me.
I'm not sure if your comment was meant for this issue/repo... 🤔

**Comment by dertieran** [comment]
> @dertieran This PR will remove the dependency for the remote module. Splitting the repo for main and renderer seems a bit over engineered to me.

Oh might by my bad, just came here because sindre mentioned me and didn't look through the code completely.
Might have misunderstood why I was mentioned :sweat_smile: 

My suggestion basically is, if the package needs functionality the app developer needs to handle the how  they want to use it from the renderer.
But I guess if only some functionality is needed from the `main` process a solution like this is also a good idea.

Maybe this is really offtopic here, because the changes for this package are more minimal.
